/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PersonasDesaparecidasRouteImport } from './routes/personas-desaparecidas'
import { Route as NumerosEmergenciaVenezuelaRouteImport } from './routes/numeros-emergencia-venezuela'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MediaSplatRouteImport } from './routes/media.$'
import { Route as InternalQuakeImageRouteImport } from './routes/internal.quake-image'
import { Route as InternalIngestRouteImport } from './routes/internal.ingest'
import { Route as ApiReportsIdPhotosRouteImport } from './routes/api.reports.$id.photos'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasDesaparecidasRoute = PersonasDesaparecidasRouteImport.update({
  id: '/personas-desaparecidas',
  path: '/personas-desaparecidas',
  getParentRoute: () => rootRouteImport,
} as any)
const NumerosEmergenciaVenezuelaRoute =
  NumerosEmergenciaVenezuelaRouteImport.update({
    id: '/numeros-emergencia-venezuela',
    path: '/numeros-emergencia-venezuela',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalQuakeImageRoute = InternalQuakeImageRouteImport.update({
  id: '/internal/quake-image',
  path: '/internal/quake-image',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalIngestRoute = InternalIngestRouteImport.update({
  id: '/internal/ingest',
  path: '/internal/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsIdPhotosRoute = ApiReportsIdPhotosRouteImport.update({
  id: '/api/reports/$id/photos',
  path: '/api/reports/$id/photos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/numeros-emergencia-venezuela': typeof NumerosEmergenciaVenezuelaRoute
  '/personas-desaparecidas': typeof PersonasDesaparecidasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/internal/ingest': typeof InternalIngestRoute
  '/internal/quake-image': typeof InternalQuakeImageRoute
  '/media/$': typeof MediaSplatRoute
  '/api/reports/$id/photos': typeof ApiReportsIdPhotosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/numeros-emergencia-venezuela': typeof NumerosEmergenciaVenezuelaRoute
  '/personas-desaparecidas': typeof PersonasDesaparecidasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/internal/ingest': typeof InternalIngestRoute
  '/internal/quake-image': typeof InternalQuakeImageRoute
  '/media/$': typeof MediaSplatRoute
  '/api/reports/$id/photos': typeof ApiReportsIdPhotosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/numeros-emergencia-venezuela': typeof NumerosEmergenciaVenezuelaRoute
  '/personas-desaparecidas': typeof PersonasDesaparecidasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/internal/ingest': typeof InternalIngestRoute
  '/internal/quake-image': typeof InternalQuakeImageRoute
  '/media/$': typeof MediaSplatRoute
  '/api/reports/$id/photos': typeof ApiReportsIdPhotosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/numeros-emergencia-venezuela'
    | '/personas-desaparecidas'
    | '/sitemap.xml'
    | '/internal/ingest'
    | '/internal/quake-image'
    | '/media/$'
    | '/api/reports/$id/photos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/numeros-emergencia-venezuela'
    | '/personas-desaparecidas'
    | '/sitemap.xml'
    | '/internal/ingest'
    | '/internal/quake-image'
    | '/media/$'
    | '/api/reports/$id/photos'
  id:
    | '__root__'
    | '/'
    | '/numeros-emergencia-venezuela'
    | '/personas-desaparecidas'
    | '/sitemap.xml'
    | '/internal/ingest'
    | '/internal/quake-image'
    | '/media/$'
    | '/api/reports/$id/photos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NumerosEmergenciaVenezuelaRoute: typeof NumerosEmergenciaVenezuelaRoute
  PersonasDesaparecidasRoute: typeof PersonasDesaparecidasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  InternalIngestRoute: typeof InternalIngestRoute
  InternalQuakeImageRoute: typeof InternalQuakeImageRoute
  MediaSplatRoute: typeof MediaSplatRoute
  ApiReportsIdPhotosRoute: typeof ApiReportsIdPhotosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas-desaparecidas': {
      id: '/personas-desaparecidas'
      path: '/personas-desaparecidas'
      fullPath: '/personas-desaparecidas'
      preLoaderRoute: typeof PersonasDesaparecidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numeros-emergencia-venezuela': {
      id: '/numeros-emergencia-venezuela'
      path: '/numeros-emergencia-venezuela'
      fullPath: '/numeros-emergencia-venezuela'
      preLoaderRoute: typeof NumerosEmergenciaVenezuelaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/quake-image': {
      id: '/internal/quake-image'
      path: '/internal/quake-image'
      fullPath: '/internal/quake-image'
      preLoaderRoute: typeof InternalQuakeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/ingest': {
      id: '/internal/ingest'
      path: '/internal/ingest'
      fullPath: '/internal/ingest'
      preLoaderRoute: typeof InternalIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/$id/photos': {
      id: '/api/reports/$id/photos'
      path: '/api/reports/$id/photos'
      fullPath: '/api/reports/$id/photos'
      preLoaderRoute: typeof ApiReportsIdPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NumerosEmergenciaVenezuelaRoute: NumerosEmergenciaVenezuelaRoute,
  PersonasDesaparecidasRoute: PersonasDesaparecidasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  InternalIngestRoute: InternalIngestRoute,
  InternalQuakeImageRoute: InternalQuakeImageRoute,
  MediaSplatRoute: MediaSplatRoute,
  ApiReportsIdPhotosRoute: ApiReportsIdPhotosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
