/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MediaSplatRouteImport } from './routes/media.$'
import { Route as ApiScrapeRouteImport } from './routes/api.scrape'
import { Route as ApiReportsIdPhotosRouteImport } from './routes/api.reports.$id.photos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeRoute = ApiScrapeRouteImport.update({
  id: '/api/scrape',
  path: '/api/scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsIdPhotosRoute = ApiReportsIdPhotosRouteImport.update({
  id: '/api/reports/$id/photos',
  path: '/api/reports/$id/photos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/scrape': typeof ApiScrapeRoute
  '/media/$': typeof MediaSplatRoute
  '/api/reports/$id/photos': typeof ApiReportsIdPhotosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/scrape': typeof ApiScrapeRoute
  '/media/$': typeof MediaSplatRoute
  '/api/reports/$id/photos': typeof ApiReportsIdPhotosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/scrape': typeof ApiScrapeRoute
  '/media/$': typeof MediaSplatRoute
  '/api/reports/$id/photos': typeof ApiReportsIdPhotosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/scrape' | '/media/$' | '/api/reports/$id/photos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/scrape' | '/media/$' | '/api/reports/$id/photos'
  id: '__root__' | '/' | '/api/scrape' | '/media/$' | '/api/reports/$id/photos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiScrapeRoute: typeof ApiScrapeRoute
  MediaSplatRoute: typeof MediaSplatRoute
  ApiReportsIdPhotosRoute: typeof ApiReportsIdPhotosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape': {
      id: '/api/scrape'
      path: '/api/scrape'
      fullPath: '/api/scrape'
      preLoaderRoute: typeof ApiScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/$id/photos': {
      id: '/api/reports/$id/photos'
      path: '/api/reports/$id/photos'
      fullPath: '/api/reports/$id/photos'
      preLoaderRoute: typeof ApiReportsIdPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiScrapeRoute: ApiScrapeRoute,
  MediaSplatRoute: MediaSplatRoute,
  ApiReportsIdPhotosRoute: ApiReportsIdPhotosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
